In [236]:
import torch

In [237]:
x = torch.arange(12, dtype=torch.float32)
print(x)

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])


In [238]:
print(f"The number of elements in x is {x.numel()}")

The number of elements in x is 12


Shaping is trivial as well.

In [239]:
print(f"shape of x: {x.shape}")

shape of x: torch.Size([12])


In [240]:
X = x.reshape(3,4)
print(f"X:\n {X}")

X:
 tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])


Multidimensional tensors are simple (This is all carried over from MATLAB it feels like to me)

In [241]:
torch.zeros((2,3,4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [242]:
torch.ones((2,3,4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [243]:
# Create a random
torch.randn(3,4)

tensor([[-0.4046,  2.0365, -1.4096,  1.6241],
        [ 0.4442, -0.2066,  1.4094, -1.0669],
        [-2.1042,  1.2272,  1.2674, -0.8260]])

In [244]:
t = torch.tensor([[2,1,4,3],[1,2,3,4],[4,3,2,1]])
print(f"t:\n {t}")

t:
 tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])


Slicing

In [245]:
print(f"X: \n {X}\n Which has a shape {X.shape}")
print("--------------------------")
print(f"X[-1]: \n {X[-1]}")
print("--------------------------")
print(f"X[1:3]: \n {X[1:3]}")
print("--------------------------")
print(f"X[:,1]: \n {X[:,1]}\n Second column")
print("--------------------------")
print(f"X[1,:]: \n {X[1,:]}\n Second row")
print("--------------------------")
# an interesting type
print(f"An interesting typo!\nX[1:,] (note the comma) gives {X[1:,]} everything but the first row")
print("--------------------------")
print("But this can be useful, for example to assign...")
X[:2,:] = 12 # everything up to the third row becomes 12
print(f"X: \n {X}")

X: 
 tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
 Which has a shape torch.Size([3, 4])
--------------------------
X[-1]: 
 tensor([ 8.,  9., 10., 11.])
--------------------------
X[1:3]: 
 tensor([[ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
--------------------------
X[:,1]: 
 tensor([1., 5., 9.])
 Second column
--------------------------
X[1,:]: 
 tensor([4., 5., 6., 7.])
 Second row
--------------------------
An interesting typo!
X[1:,] (note the comma) gives tensor([[ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]]) everything but the first row
--------------------------
But this can be useful, for example to assign...
X: 
 tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])


Operations on matrices

In [246]:
print(f"x: \n{x}")
ex = torch.exp(x)
print(f"exp(x): \n{ex}")


x: 
tensor([12., 12., 12., 12., 12., 12., 12., 12.,  8.,  9., 10., 11.])
exp(x): 
tensor([162754.7969, 162754.7969, 162754.7969, 162754.7969, 162754.7969,
        162754.7969, 162754.7969, 162754.7969,   2980.9580,   8103.0840,
         22026.4648,  59874.1406])


In [247]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x+y, x-y, x*y, x/y, x**y 

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

Concatenation

In [248]:
x = torch.arange(12,dtype=torch.float32).reshape((3,4))
y = torch.tensor([[2.0, 1, 4, 3], [1,2,3,4], [4,3,2,1]])
torch.cat((x,y),dim=0)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]])

In [249]:
torch.cat((x,y),dim=1)

tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]])

In [250]:
x == y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [251]:
x.sum()

tensor(66.)

In [252]:
a = torch.arange(3).reshape((3,1))
b = torch.arange(2).reshape((1,2))
a,b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [253]:
a+b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [254]:
a @ b

tensor([[0, 0],
        [0, 1],
        [0, 2]])

In [255]:
a * b

tensor([[0, 0],
        [0, 1],
        [0, 2]])

## Saving Memory

Some operations can cause new memory to be allocated to host results. 

In [256]:
before = id(y)
y = y + x 
id(y) == before 

False

We can optimize by doing in-place operations (or heading over to Mojo).

In [257]:
Z = torch.zeros_like(y)
print(f"id(Z): {id(Z)}")
Z[:] = x = y
print(f"id(Z): {id(Z)}")

id(Z): 4752916544
id(Z): 4752916544


Converstion to other python objects

In [258]:
import numpy 
A = x.numpy()
b = torch.from_numpy(A)
type(A), type(b)

(numpy.ndarray, torch.Tensor)

## Basic Tensor Arithmetic in PyTorch...

In [259]:
A = torch.arange(6, dtype=torch.float32).reshape(2,3)
B = A.clone()
A, A+B

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor([[ 0.,  2.,  4.],
         [ 6.,  8., 10.]]))

In [260]:
A * B

tensor([[ 0.,  1.,  4.],
        [ 9., 16., 25.]])

In [261]:
a = 2
X = torch.arange(24).reshape(2,3,4)
a  + X, (a * X).shape

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 torch.Size([2, 3, 4]))

In [262]:
X.sum()

tensor(276)

In [263]:
print(f"X.sum(axis=1) is {X.sum(axis=1)}")
print("-------------")
X.sum(axis=1, keepdims=True)

X.sum(axis=1) is tensor([[12, 15, 18, 21],
        [48, 51, 54, 57]])
-------------


tensor([[[12, 15, 18, 21]],

        [[48, 51, 54, 57]]])

In [264]:
x = torch.ones(3,dtype=torch.float32)
y = torch.ones(3,dtype=torch.float32)
x 

tensor([1., 1., 1.])

In [265]:
torch.dot(x,y)

tensor(3.)

In [266]:
torch.sum(x*y)

tensor(3.)

In [267]:
x @ y

tensor(3.)

In [268]:
A = torch.arange(12,dtype=torch.float).reshape(4,3)
A.shape, x.shape
print(f"A: \n{A}")
print(f"x: {x}")
A, x
torch.mv(A,x)
print("So this was row x column as expected...")

A: 
tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
x: tensor([1., 1., 1.])
So this was row x column as expected...


### Automatic Differentiation
This is often shortened to the term `autograd`. 

In [269]:
x = torch.arange(4.0)
x 

tensor([0., 1., 2., 3.])

In [270]:
x.requires_grad_(True)
x.grad 

In [271]:
y = 2 * torch.dot(x,x) # so y = 2*x^2
y

tensor(28., grad_fn=<MulBackward0>)

We can now take the gradient of y with resepcet to x by calling its backward method.

In [272]:
y.backward()
print(f"The gradient of x: {x.grad}")
print("Notice this is 4 * x ")
# from the documentation
"""
This attribute is None by default and becomes a Tensor the first time a call to backward() 
computes gradients for self. The attribute will then contain the gradients computed and future 
calls to backward() will accumulate (add) gradients into it.
"""

The gradient of x: tensor([ 0.,  4.,  8., 12.])
Notice this is 4 * x 


'\nThis attribute is None by default and becomes a Tensor the first time a call to backward() \ncomputes gradients for self. The attribute will then contain the gradients computed and future \ncalls to backward() will accumulate (add) gradients into it.\n'

In [273]:
x.grad == 4 * x

tensor([True, True, True, True])

In [274]:
# let's reset and treat y as another f(x)
x.grad.zero_() # reset the gradient
y = x.sum()
y.backward()
"""
Computes the gradient of current tensor wrt graph leaves.

The graph is differentiated using the chain rule. If the tensor is non-scalar 
(i.e. its data has more than one element) and requires gradient, the function 
additionally requires specifying gradient. It should be a tensor of matching 
type and location, that contains the gradient of the differentiated function w.r.t. self.
"""
print(f"Recall x = {x}")
print(f"The new gradient is {x.grad}")

The new gradient is tensor([1., 1., 1., 1.])
